##
## Check GETTING_STARTED.md for additional properties and their default values.
##

liferay.workspace.bundle.dist.include.metadata=true
liferay.workspace.modules.dir=modules
liferay.workspace.themes.dir=themes
liferay.workspace.wars.dir=modules
microsoft.translator.subscription.key=
# liferay.workspace.product=dxp-2025.q4.5
liferay.workspace.product=dxp-2026.q1.1-lts

com.liferay.portal.tools.service.builder.version=1.0.509
com.liferay.portal.tools.rest.builder=1.0.419

