
    #
    # Input a list of comma delimited paths that will be excluded by the source
    # formatter.
    #
    source.formatter.excludes=\
        **/bundles*/**
upgrade.to.liferay.version=7.4
upgrade.to.release.version=2026.q1.1
